/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Playwright .NET",
  "tagline": "Fast and reliable end-to-end testing for modern web apps",
  "url": "https://playwright.dev",
  "baseUrl": "/dotnet/",
  "organizationName": "microsoft",
  "projectName": "playwright.dev",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "throw",
  "scripts": [
    "/dotnet/js/redirection.js"
  ],
  "favicon": "img/playwright-logo.svg",
  "themeConfig": {
    "colorMode": {
      "defaultMode": "dark",
      "respectPrefersColorScheme": true,
      "disableSwitch": false
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [
        "csharp",
        "bash",
        "batch",
        "powershell"
      ],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "navbar": {
      "title": "Playwright for .NET",
      "logo": {
        "alt": "Playwright logo",
        "src": "img/playwright-logo.svg"
      },
      "items": [
        {
          "type": "doc",
          "docId": "intro",
          "label": "Docs",
          "position": "left"
        },
        {
          "type": "doc",
          "docId": "api/class-playwright",
          "label": "API",
          "position": "left"
        },
        {
          "href": "https://github.com/microsoft/playwright-dotnet",
          "position": "right",
          "className": "header-github-link",
          "aria-label": "GitHub repository"
        },
        {
          "label": ".NET",
          "position": "left",
          "items": [
            {
              "label": ".NET",
              "data-language-prefix": "/dotnet/",
              "href": "#"
            },
            {
              "label": "Node.js",
              "data-language-prefix": "/",
              "href": "#"
            },
            {
              "label": "Python",
              "data-language-prefix": "/python/",
              "href": "#"
            },
            {
              "label": "Java",
              "data-language-prefix": "/java/",
              "href": "#"
            }
          ]
        },
        {
          "to": "/community/welcome",
          "label": "Community",
          "position": "left",
          "activeBaseRegex": "/community/"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Docs",
          "items": [
            {
              "label": "Getting started",
              "to": "docs/intro"
            },
            {
              "label": "API reference",
              "to": "docs/api/class-playwright"
            }
          ]
        },
        {
          "title": "Community",
          "items": [
            {
              "label": "Stack Overflow",
              "href": "https://stackoverflow.com/questions/tagged/playwright"
            },
            {
              "label": "Slack",
              "href": "https://aka.ms/playwright-slack"
            },
            {
              "label": "Twitter",
              "href": "https://twitter.com/playwrightweb"
            }
          ]
        },
        {
          "title": "More",
          "items": [
            {
              "label": "GitHub",
              "href": "https://github.com/microsoft/playwright-dotnet"
            },
            {
              "label": "YouTube",
              "href": "https://www.youtube.com/channel/UC46Zj8pDH5tDosqm1gd7WTg"
            },
            {
              "label": "Conference videos",
              "href": "/community/conference-videos"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2022 Microsoft"
    },
    "algolia": {
      "indexName": "playwright-dotnet",
      "appId": "K09ICMCV6X",
      "apiKey": "a5b64422711c37ab6a0ce4d86d16cdd9",
      "contextualSearch": true,
      "searchParameters": {},
      "searchPagePath": "search"
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "themes": [
    [
      "/home/runner/work/playwright.dev/playwright.dev/node_modules/@docusaurus/theme-classic/lib/index.js",
      {
        "customCss": "/home/runner/work/playwright.dev/playwright.dev/src/css/custom.css"
      }
    ],
    "@docusaurus/theme-search-algolia"
  ],
  "plugins": [
    [
      "/home/runner/work/playwright.dev/playwright.dev/node_modules/@docusaurus/plugin-content-docs/lib/index.js",
      {
        "sidebarPath": "/home/runner/work/playwright.dev/playwright.dev/sidebars.js",
        "versions": {
          "stable": {
            "badge": false
          }
        }
      }
    ],
    [
      "content-docs",
      {
        "id": "community",
        "path": "community",
        "routeBasePath": "community",
        "sidebarPath": "/home/runner/work/playwright.dev/playwright.dev/sidebarCommunity.js"
      }
    ],
    "/home/runner/work/playwright.dev/playwright.dev/node_modules/@docusaurus/plugin-content-pages/lib/index.js",
    "/home/runner/work/playwright.dev/playwright.dev/plugins/playwright-analytics-integration/lib/index.js",
    "/home/runner/work/playwright.dev/playwright.dev/node_modules/@docusaurus/plugin-sitemap/lib/index.js"
  ],
  "customFields": {
    "repositoryName": "playwright-dotnet"
  },
  "trailingSlash": false,
  "webpack": {},
  "baseUrlIssueBanner": true,
  "i18n": {
    "defaultLocale": "en",
    "path": "i18n",
    "locales": [
      "en"
    ],
    "localeConfigs": {}
  },
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "presets": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false
};
